# python-ci.yml
name: basic CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-run-pytest:

    runs-on: ubuntu-latest

    steps:
    # First step (unnamed here) is to checkout to the branch that triggered the event
    # if you create a new branch, this step will checkout to that branch (e.g. ci-github-action-setup)
    - uses: actions/checkout@v3  # pre-made script provided by GitHub that will checkout to the branch that triggered the event

    # Second step: install python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

# Third step: install python packages using a requirements file. These packages are needed to run create a virtual environment and run tests
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip cython wheel
        pip install -r requirements.txt

    # Fourth step: run tests with Pytest
    - name: Run tests
      run: make
